// Mocks generated by Mockito 5.4.4 from annotations
// in story_creator/test/unit/user_display_name_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:story_creator/domain/usecases/authentication_user/user_get_displayname.dart'
    as _i3;
import 'package:story_creator/domain/usecases/authentication_user/user_update_current_displayname.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRef_0<State extends Object?> extends _i1.SmartFake
    implements _i2.Ref<State> {
  _FakeRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCurrentUserDisplayNameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUserDisplayNameUseCase extends _i1.Mock
    implements _i3.GetCurrentUserDisplayNameUseCase {
  MockGetCurrentUserDisplayNameUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ref<Object?> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeRef_0<Object?>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.Ref<Object?>);

  @override
  _i4.Future<String> invoke() => (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #invoke,
            [],
          ),
        )),
      ) as _i4.Future<String>);
}

/// A class which mocks [UpdateCurrentUserDisplayNameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateCurrentUserDisplayNameUseCase extends _i1.Mock
    implements _i6.UpdateCurrentUserDisplayNameUseCase {
  MockUpdateCurrentUserDisplayNameUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ref<Object?> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeRef_0<Object?>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.Ref<Object?>);

  @override
  _i4.Future<void> invoke(String? displayName) => (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [displayName],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
